<?php
/**
 * UndeliverableContactsApi
 * PHP version 5
 *
 * @category Class
 * @package  METHIS
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * METHIS Master Data
 *
 * Documentation for METHIS Master Data API for centralized master data storage
 *
 * OpenAPI spec version: 1.1.0
 * Contact: info@datamill.solutions
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace METHIS;

use \METHIS\ApiClient;
use \METHIS\ApiException;
use \METHIS\Configuration;
use \METHIS\ObjectSerializer;

/**
 * UndeliverableContactsApi Class Doc Comment
 *
 * @category Class
 * @package  METHIS
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class UndeliverableContactsApi
{
    /**
     * API Client
     *
     * @var \METHIS\ApiClient instance of the ApiClient
     */
    protected $apiClient;

    /**
     * Constructor
     *
     * @param \METHIS\ApiClient|null $apiClient The api client to use
     */
    public function __construct(\METHIS\ApiClient $apiClient = null)
    {
        if ($apiClient === null) {
            $apiClient = new ApiClient();
            $apiClient->getConfig()->setHost('https://master-data.methis.at/api');
        }

        $this->apiClient = $apiClient;
    }

    /**
     * Get API client
     *
     * @return \METHIS\ApiClient get the API client
     */
    public function getApiClient()
    {
        return $this->apiClient;
    }

    /**
     * Set the API client
     *
     * @param \METHIS\ApiClient $apiClient set the API client
     *
     * @return UndeliverableContactsApi
     */
    public function setApiClient(\METHIS\ApiClient $apiClient)
    {
        $this->apiClient = $apiClient;
        return $this;
    }

    /**
     * Operation searchUndeliverableContact
     *
     * Searches for name and addresses and detects if the contact has moved or is deceased
     *
     * @param string $key The API key which you got for authenticating against the API (required)
     * @param string $first_name  (required)
     * @param string $last_name  (required)
     * @param string $country_code 2 digit ISO country code (required)
     * @param string $zip Zip code of the address (required)
     * @param string $street Street name without housenumber or any other additions. (required)
     * @throws \METHIS\ApiException on non-2xx response
     * @return \METHIS\UndeliverableContactResponse
     */
    public function searchUndeliverableContact($key, $first_name, $last_name, $country_code, $zip, $street)
    {
        list($response) = $this->searchUndeliverableContactWithHttpInfo($key, $first_name, $last_name, $country_code, $zip, $street);
        return $response;
    }

    /**
     * Operation searchUndeliverableContactWithHttpInfo
     *
     * Searches for name and addresses and detects if the contact has moved or is deceased
     *
     * @param string $key The API key which you got for authenticating against the API (required)
     * @param string $first_name  (required)
     * @param string $last_name  (required)
     * @param string $country_code 2 digit ISO country code (required)
     * @param string $zip Zip code of the address (required)
     * @param string $street Street name without housenumber or any other additions. (required)
     * @throws \METHIS\ApiException on non-2xx response
     * @return array of \METHIS\UndeliverableContactResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function searchUndeliverableContactWithHttpInfo($key, $first_name, $last_name, $country_code, $zip, $street)
    {
        // verify the required parameter 'key' is set
        if ($key === null) {
            throw new \InvalidArgumentException('Missing the required parameter $key when calling searchUndeliverableContact');
        }
        if ((strlen($key) > 40)) {
            throw new \InvalidArgumentException('invalid length for "$key" when calling UndeliverableContactsApi.searchUndeliverableContact, must be smaller than or equal to 40.');
        }
        if ((strlen($key) < 40)) {
            throw new \InvalidArgumentException('invalid length for "$key" when calling UndeliverableContactsApi.searchUndeliverableContact, must be bigger than or equal to 40.');
        }

        // verify the required parameter 'first_name' is set
        if ($first_name === null) {
            throw new \InvalidArgumentException('Missing the required parameter $first_name when calling searchUndeliverableContact');
        }
        if ((strlen($first_name) > 30)) {
            throw new \InvalidArgumentException('invalid length for "$first_name" when calling UndeliverableContactsApi.searchUndeliverableContact, must be smaller than or equal to 30.');
        }
        if ((strlen($first_name) < 1)) {
            throw new \InvalidArgumentException('invalid length for "$first_name" when calling UndeliverableContactsApi.searchUndeliverableContact, must be bigger than or equal to 1.');
        }

        // verify the required parameter 'last_name' is set
        if ($last_name === null) {
            throw new \InvalidArgumentException('Missing the required parameter $last_name when calling searchUndeliverableContact');
        }
        if ((strlen($last_name) > 100)) {
            throw new \InvalidArgumentException('invalid length for "$last_name" when calling UndeliverableContactsApi.searchUndeliverableContact, must be smaller than or equal to 100.');
        }
        if ((strlen($last_name) < 1)) {
            throw new \InvalidArgumentException('invalid length for "$last_name" when calling UndeliverableContactsApi.searchUndeliverableContact, must be bigger than or equal to 1.');
        }

        // verify the required parameter 'country_code' is set
        if ($country_code === null) {
            throw new \InvalidArgumentException('Missing the required parameter $country_code when calling searchUndeliverableContact');
        }
        if ((strlen($country_code) > 2)) {
            throw new \InvalidArgumentException('invalid length for "$country_code" when calling UndeliverableContactsApi.searchUndeliverableContact, must be smaller than or equal to 2.');
        }
        if ((strlen($country_code) < 2)) {
            throw new \InvalidArgumentException('invalid length for "$country_code" when calling UndeliverableContactsApi.searchUndeliverableContact, must be bigger than or equal to 2.');
        }

        // verify the required parameter 'zip' is set
        if ($zip === null) {
            throw new \InvalidArgumentException('Missing the required parameter $zip when calling searchUndeliverableContact');
        }
        if ((strlen($zip) > 20)) {
            throw new \InvalidArgumentException('invalid length for "$zip" when calling UndeliverableContactsApi.searchUndeliverableContact, must be smaller than or equal to 20.');
        }
        if ((strlen($zip) < 1)) {
            throw new \InvalidArgumentException('invalid length for "$zip" when calling UndeliverableContactsApi.searchUndeliverableContact, must be bigger than or equal to 1.');
        }

        // verify the required parameter 'street' is set
        if ($street === null) {
            throw new \InvalidArgumentException('Missing the required parameter $street when calling searchUndeliverableContact');
        }
        if ((strlen($street) > 100)) {
            throw new \InvalidArgumentException('invalid length for "$street" when calling UndeliverableContactsApi.searchUndeliverableContact, must be smaller than or equal to 100.');
        }
        if ((strlen($street) < 1)) {
            throw new \InvalidArgumentException('invalid length for "$street" when calling UndeliverableContactsApi.searchUndeliverableContact, must be bigger than or equal to 1.');
        }

        // parse inputs
        $resourcePath = "/undeliverable-contact/search";
        $httpBody = '';
        $queryParams = [];
        $headerParams = [];
        $formParams = [];
        $_header_accept = $this->apiClient->selectHeaderAccept(['application/json']);
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(['multipart/form-data']);

        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        // form params
        if ($key !== null) {
            $formParams['key'] = $this->apiClient->getSerializer()->toFormValue($key);
        }
        // form params
        if ($first_name !== null) {
            $formParams['first_name'] = $this->apiClient->getSerializer()->toFormValue($first_name);
        }
        // form params
        if ($last_name !== null) {
            $formParams['last_name'] = $this->apiClient->getSerializer()->toFormValue($last_name);
        }
        // form params
        if ($country_code !== null) {
            $formParams['country_code'] = $this->apiClient->getSerializer()->toFormValue($country_code);
        }
        // form params
        if ($zip !== null) {
            $formParams['zip'] = $this->apiClient->getSerializer()->toFormValue($zip);
        }
        // form params
        if ($street !== null) {
            $formParams['street'] = $this->apiClient->getSerializer()->toFormValue($street);
        }
        
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'POST',
                $queryParams,
                $httpBody,
                $headerParams,
                '\METHIS\UndeliverableContactResponse',
                '/undeliverable-contact/search'
            );

            return [$this->apiClient->getSerializer()->deserialize($response, '\METHIS\UndeliverableContactResponse', $httpHeader), $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\METHIS\UndeliverableContactResponse', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\METHIS\ErrorUnauthorized', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\METHIS\ErrorForbidden', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\METHIS\ErrorNotFound', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 405:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\METHIS\ErrorNotAllowed', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 422:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\METHIS\ErrorMissingParameters', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\METHIS\ErrorInternalError', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 503:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\METHIS\ErrorServiceUnavailable', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }

    /**
     * Operation searchUndeliverableContacts
     *
     * Batch search for name and addresses and detects if the contact has moved or is deceased.
     *
     * @param string $key The API key which you got for authenticating against the API (required)
     * @param string $batch JSON encoded request data as array of single requests. For structure of single request please see /undeliverable-contact/search route (required)
     * @throws \METHIS\ApiException on non-2xx response
     * @return \METHIS\UndeliverableContactResponse[]
     */
    public function searchUndeliverableContacts($key, $batch)
    {
        list($response) = $this->searchUndeliverableContactsWithHttpInfo($key, $batch);
        return $response;
    }

    /**
     * Operation searchUndeliverableContactsWithHttpInfo
     *
     * Batch search for name and addresses and detects if the contact has moved or is deceased.
     *
     * @param string $key The API key which you got for authenticating against the API (required)
     * @param string $batch JSON encoded request data as array of single requests. For structure of single request please see /undeliverable-contact/search route (required)
     * @throws \METHIS\ApiException on non-2xx response
     * @return array of \METHIS\UndeliverableContactResponse[], HTTP status code, HTTP response headers (array of strings)
     */
    public function searchUndeliverableContactsWithHttpInfo($key, $batch)
    {
        // verify the required parameter 'key' is set
        if ($key === null) {
            throw new \InvalidArgumentException('Missing the required parameter $key when calling searchUndeliverableContacts');
        }
        if ((strlen($key) > 40)) {
            throw new \InvalidArgumentException('invalid length for "$key" when calling UndeliverableContactsApi.searchUndeliverableContacts, must be smaller than or equal to 40.');
        }
        if ((strlen($key) < 40)) {
            throw new \InvalidArgumentException('invalid length for "$key" when calling UndeliverableContactsApi.searchUndeliverableContacts, must be bigger than or equal to 40.');
        }

        // verify the required parameter 'batch' is set
        if ($batch === null) {
            throw new \InvalidArgumentException('Missing the required parameter $batch when calling searchUndeliverableContacts');
        }
        if ((strlen($batch) < 1)) {
            throw new \InvalidArgumentException('invalid length for "$batch" when calling UndeliverableContactsApi.searchUndeliverableContacts, must be bigger than or equal to 1.');
        }

        // parse inputs
        $resourcePath = "/undeliverable-contacts/search";
        $httpBody = '';
        $queryParams = [];
        $headerParams = [];
        $formParams = [];
        $_header_accept = $this->apiClient->selectHeaderAccept(['application/json']);
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(['multipart/form-data']);

        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        // form params
        if ($key !== null) {
            $formParams['key'] = $this->apiClient->getSerializer()->toFormValue($key);
        }
        // form params
        if ($batch !== null) {
            $formParams['batch'] = $this->apiClient->getSerializer()->toFormValue($batch);
        }
        
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'POST',
                $queryParams,
                $httpBody,
                $headerParams,
                '\METHIS\UndeliverableContactResponse[]',
                '/undeliverable-contacts/search'
            );

            return [$this->apiClient->getSerializer()->deserialize($response, '\METHIS\UndeliverableContactResponse[]', $httpHeader), $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\METHIS\UndeliverableContactResponse[]', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\METHIS\ErrorUnauthorized', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\METHIS\ErrorForbidden', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\METHIS\ErrorNotFound', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 405:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\METHIS\ErrorNotAllowed', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 422:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\METHIS\ErrorMissingParameters', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\METHIS\ErrorInternalError', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 503:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\METHIS\ErrorServiceUnavailable', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }
}
