<?php
/**
 * MovedContactResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  METHIS
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * METHIS Master Data
 *
 * Documentation for METHIS Master Data API for centralized master data storage
 *
 * OpenAPI spec version: 1.1.0
 * Contact: info@datamill.solutions
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace METHIS;

/**
 * MovedContactResponseTest Class Doc Comment
 *
 * @category    Class */
// * @description Response of found moved contact
/**
 * @package     METHIS
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MovedContactResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "MovedContactResponse"
     */
    public function testMovedContactResponse()
    {

    }

    /**
     * Test attribute "first_name"
     */
    public function testPropertyFirstName()
    {

    }

    /**
     * Test attribute "last_name"
     */
    public function testPropertyLastName()
    {

    }

    /**
     * Test attribute "country_old"
     */
    public function testPropertyCountryOld()
    {

    }

    /**
     * Test attribute "street_old"
     */
    public function testPropertyStreetOld()
    {

    }

    /**
     * Test attribute "timestamp"
     */
    public function testPropertyTimestamp()
    {

    }

    /**
     * Test attribute "gender"
     */
    public function testPropertyGender()
    {

    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {

    }

    /**
     * Test attribute "title_of_nobility"
     */
    public function testPropertyTitleOfNobility()
    {

    }

    /**
     * Test attribute "house_number_old"
     */
    public function testPropertyHouseNumberOld()
    {

    }

    /**
     * Test attribute "house_number_addition_old"
     */
    public function testPropertyHouseNumberAdditionOld()
    {

    }

    /**
     * Test attribute "street_addition_old"
     */
    public function testPropertyStreetAdditionOld()
    {

    }

    /**
     * Test attribute "city_old"
     */
    public function testPropertyCityOld()
    {

    }

    /**
     * Test attribute "zip_old"
     */
    public function testPropertyZipOld()
    {

    }

    /**
     * Test attribute "country_new"
     */
    public function testPropertyCountryNew()
    {

    }

    /**
     * Test attribute "zip_new"
     */
    public function testPropertyZipNew()
    {

    }

    /**
     * Test attribute "street_new"
     */
    public function testPropertyStreetNew()
    {

    }

    /**
     * Test attribute "house_number_new"
     */
    public function testPropertyHouseNumberNew()
    {

    }

    /**
     * Test attribute "house_number_addition_new"
     */
    public function testPropertyHouseNumberAdditionNew()
    {

    }

    /**
     * Test attribute "street_addition_new"
     */
    public function testPropertyStreetAdditionNew()
    {

    }

    /**
     * Test attribute "city_new"
     */
    public function testPropertyCityNew()
    {

    }

}
